import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Add other head elements as needed */}
      </Head>
      <body className={inter.className}>
        <nav className="bg-gray-800 p-4">
          <div className="container mx-auto">
            <div className="flex items-center justify-between">
              <div>
                <Link href="/" passHref>
                  <span className="text-white text-xl font-bold cursor-pointer">Your App Name</span>
                </Link>
              </div>
              <div className="flex space-x-4">
                <Link href="/home" passHref>
                  <span className="text-white cursor-pointer">Home</span>
                </Link>
                <Link href="/feeds" passHref>
                  <span className="text-white cursor-pointer">Feeds</span>
                </Link>
                {/* Add more links as needed */}
              </div>
            </div>
          </div>
        </nav>
        <div>
          {children}
        </div>
      </body>
    </>
  );
};

export default RootLayout;
